CREATE ROLE guidein_app LOGIN PASSWORD 'guidein-app-test'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE guidein_migrator LOGIN PASSWORD 'guidein-migrator-test'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT USAGE, CREATE ON SCHEMA public TO guidein_migrator;
GRANT USAGE ON SCHEMA public TO guidein_app;
